# This file is kept for reference but railway.json is the primary configuration
# See railway.json for the actual deployment configuration

[build]
builder = "nixpacks"
nixpacksConfigPath = "./nixpacks.toml"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"

# These are just examples and should be set in Railway environment variables
# JWT_SECRET
# MONGODB_URI
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET
# OPENAI_API_KEY (if needed)
# etc.